### Check the API Caching status endpoint.
http://localhost:3000/api/caching/status

### POST a cache record for a key
POST http://localhost:3000/api/caching/put/1234 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Get a cache record for a key
http://localhost:3000/api/caching/get/1234


### Delete a cache record for a key
DELETE http://localhost:3000/api/caching/delete/1234


